version: '2'
services:
   wordpress:
      image: wordpress:4.5
      container_name: wordpress-con
      depends_on:
         - db
      links:
         - db:mysql
      ports:
         - 80:80
      environment:
         WORDPRESS_DB_HOST: db:3306
         WORDPRESS_DB_PASSWORD: wordpress
         WORDPRESS_DB_USER: wordpress
      restart: always
   db:
      image: mariadb:10.1
      container_name: baza
      volumes_from:
         - db-data
      environment:
         MYSQL_ROOT_PASSWORD: example
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: wordpress
      restart: always
   db-data:
      image: mariadb:10.1
      container_name: dysk_baza
      volumes:
         - ./volumes/db:/var/lib/mysql
      command: "true"
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: php_admin
      ports:
         - 8080:80
      links:
         - db
      environment:
         PMA_HOST: db 
